resources/css/app.css
resources/css/typography.css
resources/fonts/.gitignore
resources/js/App.vue
resources/js/components/RectangleButton.vue
tailwind.config.js

verify code using api

---

app/Console/Commands/ImportAirtable.php
app/Models/Code.php
composer.json
composer.lock
config/airtable.php

add tapp/laravel-airtable + command import:airtable

---

package-lock.json
package.json
resources/js/App.vue
resources/js/app.js
resources/js/components/Header.vue
resources/js/stores/ItemsStore.js
resources/js/views/Detail.vue
resources/js/views/Home.vue
resources/lang/sk.json
tailwind.config.js

used [Pinia](https://pinia.vuejs.org) for store
rewrote to use [Composition API](https://vuejs.org/api/composition-api-setup.html)
tried [<script setup>](https://vuejs.org/api/sfc-script-setup.html) in new `Header` component

Nsng 12 save artwork

---

app/Http/Resources/ItemResource.php
resources/js/components/ItemImage.vue
resources/js/components/ItemImageLightbox.vue
resources/js/components/ThumbRow.vue
resources/js/views/Collection.vue
resources/js/views/Detail.vue
resources/lang/sk.json

Nsng 22 detail tweaks

---

resources/js/components/CardModal.vue
resources/js/views/Collection.vue
resources/js/views/Home.vue
resources/lang/sk.json
tailwind.config.js

Nsng 34 popup demo only

---

resources/js/App.vue
resources/js/components/ItemImageLightbox.vue
resources/js/views/Collection.vue
resources/js/views/Detail.vue
resources/js/views/Home.vue
resources/views/app.blade.php
tailwind.config.js

fix desktop view + always fit screen height on mobile

Desktop view

---

app/Models/Collection.php
composer.json
composer.lock
config/hashids.php
database/migrations/2022_05_09_224547_create_collections_table.php
resources/js/app.js
resources/js/stores/ItemsStore.js
resources/js/views/Collection.vue
resources/lang/sk.json
routes/api.php

before:
after creating shareable url:

Nsng 47 share url

---

resources/js/components/Header.vue
resources/views/code-svg.blade.php
resources/views/print.blade.php
routes/web.php

Nsng 40 generate svg

---

app/Console/Commands/ImportAirtable.php
app/Http/Resources/ItemResource.php
database/migrations/2022_08_23_095553_add_offset_top_to_codes.php
resources/js/app.js
resources/js/components/ItemImage.vue
resources/js/components/ItemImageLightbox.vue
resources/js/components/ItemImageMovable.vue
resources/js/views/Detail.vue
routes/api.php

add route `/edit/{id}` to reposition image and to get `offsetTop` value 
store `offsetTop` in `codes` table
import `offsetTop` from airtable

Nsng 58 smart crop preview image

---

resources/js/stores/ItemsStore.js

fix: clear collection link

---

resources/js/components/Header.vue
tailwind.config.js

Change popup to transition.
Fix tooltip not showing up because of conflicting actions
https://user-images.githubusercontent.com/28804184/186854167-b325400b-a7e8-4a4e-a3e5-931b02fc685e.mov

fix: transition on add to collection

---

resources/js/App.vue
resources/js/app.js
resources/js/components/Header.vue
resources/js/consts.js
resources/js/stores/DetailStore.js
resources/js/views/Collection.vue
resources/js/views/Detail.vue
resources/js/views/Home.vue

Seperated Header from Views 
Needed for page transitions to work eventually.

chore: separate header logic from screens

---

resources/js/stores/ItemsStore.js

Functionality:
https://user-images.githubusercontent.com/28804184/188314114-5193ee89-4368-44ea-8cdb-8f6c7964693a.mov
Fix:
https://user-images.githubusercontent.com/28804184/188314108-78328c81-9724-4487-ba84-b51bc309c248.mov

fix: item ids not being saved to store

---

app/Console/Commands/ImportAirtable.php
database/migrations/2022_11_04_161134_add_airtable_id_to_codes_table.php

Temporary change for future splitting of Code model

import airtable id to codes

---

resources/js/components/AuthoritySummary.vue
resources/js/components/ConfirmButton.vue
resources/js/components/WebumeniaButton.vue
resources/js/views/Detail.vue

Nsng 75 webumenia button

---

app/Console/Commands/ImportItems.php
database/migrations/2022_11_07_221135_add_title_to_items_table.php
resources/lang/sk.json
resources/views/items.blade.php
resources/views/layouts/master.blade.php
resources/views/sections.blade.php
routes/web.php

https://jira.sng.sk/browse/NSNG-83

code lists

---

resources/js/components/ItemThumbnail.vue
resources/js/components/Thumbnail.vue
resources/js/views/Collection.vue
resources/js/views/SectionDetail.vue
tailwind.config.js

https://jira.sng.sk/browse/NSNG-82

thumbnail redesign

---

.gitignore
public/mix-manifest.json
webpack.mix.js

https://jira.sng.sk/browse/NSNG-92

mix version

---

resources/views/code-svg.blade.php
resources/views/items.blade.php
resources/views/sections.blade.php

more info https://jira.sng.sk/browse/NSNG-100

update code svg

---

app/Console/Commands/ImportAuthorities.php
app/Console/Commands/ImportItems.php
app/DataMappers/AirtableMapper.php
app/Http/Resources/AuthorityResource.php
app/Http/Resources/ItemResource.php
app/Jobs/ImportAuthoritiesJob.php
app/Models/Authority.php
config/airtable.php
database/migrations/2022_11_09_124256_create_authorities_table.php
database/migrations/2022_11_14_044847_drop_author_description_from_items_table.php
resources/js/components/AuthorityDetails.vue
resources/js/views/ItemDetail.vue
routes/web.php

https://jira.sng.sk/browse/NSNG-87

authority importer

---

app/Console/Commands/ImportExhibitions.php
app/Console/Commands/ImportItems.php
app/Console/Commands/ImportSections.php
app/DataMappers/AirtableMapper.php
app/Jobs/ImportExhibitionsJob.php
app/Models/Code.php
app/Models/Exhibition.php
config/airtable.php
database/migrations/2022_11_16_105822_create_exhibitions_table.php
database/migrations/2022_11_16_110619_add_exhibition_id_to_codes_table.php
resources/views/items.blade.php
resources/views/sections.blade.php
routes/web.php

Nsng 81 store exhibition in codes

---

app/Console/Commands/ImportStories.php
app/DataMappers/AirtableMapper.php
app/Jobs/ImportStoriesJob.php
app/Models/Item.php
app/Models/Section.php
app/Models/Story.php
app/Models/StoryLink.php
app/Providers/AppServiceProvider.php
composer.json
composer.lock
config/airtable.php
config/media-library.php
database/migrations/2022_11_09_163906_create_stories_table.php
database/migrations/2022_11_09_164014_create_story_links_table.php
database/migrations/2022_11_09_172756_create_story_story_link_table.php
database/migrations/2022_11_14_203337_create_media_table.php

https://jira.sng.sk/browse/NSNG-86

Nsng 86 story importer

---

routes/web.php

sort `/items` and `/sections` by exhibition

sort /items and /sections by exhibition

---

app/Http/Resources/StoryResource.php
app/Models/Story.php

https://jira.sng.sk/browse/NSNG-108

fix story formatting

---

app/DataMappers/AirtableMapper.php
app/Http/Resources/StoryResource.php
app/Providers/AppServiceProvider.php
app/Video/VimeoApi.php
config/services.php
database/migrations/2022_11_26_191949_add_video_to_stories_table.php
resources/js/views/Story.vue

https://jira.sng.sk/browse/NSNG-94
Displays only video thumbnail for now.

Nsng 94 video import

---

resources/js/components/CodePanel.vue
resources/js/components/FavouritesCount.vue
resources/js/components/Header.vue
resources/js/views/Story.vue
tailwind.config.js

https://jira.sng.sk/browse/NSNG-96
There is some code duplication however since the homepage will eventually change to `Story` I find it unnecessary to make it reusable at this point.

code panel

---

resources/js/app.js
resources/js/views/SectionDetail.vue
resources/lang/sk.json

translate section

---

routes/web.php

include stories in import

---

app/Exceptions/Handler.php
composer.json
composer.lock

https://jira.sng.sk/browse/NSNG-149

setup sentry in laravel

---

app/Console/Commands/ImportItems.php
app/Http/Resources/ItemResource.php
database/migrations/2022_12_07_001344_add_author_description_to_items_table.php
resources/js/components/AuthorDetails.vue
resources/js/components/AuthorSummary.vue
resources/js/views/ItemDetail.vue

https://jira.sng.sk/browse/NSNG-151

item author description

---

.prettierrc.json
app/Http/Resources/ItemResource.php
app/Http/Resources/SectionResource.php
app/Http/Resources/StoryResource.php
app/Providers/AppServiceProvider.php

https://jira.sng.sk/browse/NSNG-159

convert markdown soft breaks to html

---

resources/views/app.blade.php

https://jira.sng.sk/browse/NSNG-126

tracking codes

---

resources/js/stores/InteractionStore.js

enable code panel peeking

---

public/site.webmanifest
resources/views/layouts/master.blade.php

make app run fullscreen + enforce portrait mode

---

app/Http/Resources/PlaceResource.php

https://jira.sng.sk/browse/NSNG-203

include video title/subtitle in PlaceResource

---

resources/js/components/About.vue
resources/lang/sk.json
tailwind.config.js

https://jira.sng.sk/browse/NSNG-202

Nsng 202 reset en

---

resources/js/components/About.vue
resources/lang/sk.json
tailwind.config.js

https://jira.sng.sk/browse/NSNG-132

interaction reset

---

resources/js/components/InteractionStory.vue
resources/js/stores/InteractionStore.js
resources/js/stores/StoryStore.js

https://jira.sng.sk/browse/NSNG-196

visited links

---

app/Http/Resources/ItemResource.php
app/Http/Resources/PlaceResource.php
app/Http/Resources/SectionResource.php
resources/js/views/ItemDetail.vue
resources/js/views/PlaceDetail.vue
resources/js/views/SectionDetail.vue

https://jira.sng.sk/browse/NSNG-169

display locations

---

resources/js/components/InteractionStory.vue
resources/js/stores/InteractionStore.js

https://jira.sng.sk/browse/NSNG-212

interaction has visited all links

---

app/Models/Location.php
resources/js/components/About.vue
resources/lang/sk.json

Nsng 231 fix location formatter

---

resources/js/components/Bucketlist.vue
resources/js/components/CodePanel.vue
resources/js/components/Header.vue
resources/js/components/Timeline.vue
resources/js/components/ViewedItemsCount.vue
resources/js/stores/InteractionStore.js
resources/js/stores/ItemStore.js
resources/js/views/ItemDetail.vue
resources/js/views/PlaceDetail.vue
resources/js/views/SectionDetail.vue

https://jira.sng.sk/browse/NSNG-279

viewed entities on access of detail

---

app/Models/Code.php

new limit is the combination between `1 - 6` dots

change generated code dots limit

---

resources/js/components/Bucketlist.vue

https://github.com/SlovakNationalGallery/atlas.sng.sk/assets/28804184/e95dc6ca-8f56-43df-9acd-de8dbb1d5640

Nsng 291 -  The user can enter code by tapping the locked bucketlist item

---

resources/js/views/ItemDetail.vue

Nsng 294 -  Back button on artwork detail

---

resources/js/components/Bucketlist.vue
resources/js/views/RewardDetail.vue

https://github.com/SlovakNationalGallery/atlas.sng.sk/assets/28804184/9062c8a4-1e93-4914-9a53-818ea555f85d
WDYT Igor
Should I remove the code form the RewardDetail.vue that is handling this situation also?

Nsng 295 -  Séria mesiaca (komponent so zámkom) nie je klikateľný

---

resources/js/views/ItemDetail.vue
resources/lang/sk.json

Nsng 292 completed bucket list item detail

---

app/Http/Resources/AuthorityResource.php

chore: format authority birth_place death_place

---

resources/js/views/SectionDetail.vue

I would like to test it with data :)
But I believe @igor-kamil you will be able to check if It works by reading the code

Nsng 316 cover obrázok

---

app/Http/Resources/ItemResource.php
package-lock.json
package.json
resources/js/components/ImageLightbox.vue
resources/js/components/ZoomViewer.vue
resources/js/views/ItemDetail.vue

https://github.com/SlovakNationalGallery/atlas.sng.sk/assets/28804184/d82a8cae-b402-4132-8445-78bc42a8a672

feat: add zoom on images

---

resources/js/components/ViewedItemsCount.vue
resources/lang/sk.json

add missing translation

---

resources/js/views/SectionDetail.vue

fix: use ItemImage instead of Lightbox for SectionDetail

---

resources/css/app.css
resources/js/components/InteractionStory.vue
resources/js/views/ItemDetail.vue
resources/js/views/LockedItemDetail.vue
resources/js/views/PlaceDetail.vue
resources/js/views/RewardDetail.vue
resources/js/views/SectionDetail.vue

Rewrite tailwind pre-flight for markdown class.

Nsng 325 format bullet list

---

app/Http/Resources/ItemResource.php
app/Jobs/ImportItemsJob.php
app/Models/Item.php
database/migrations/2023_08_11_145521_add_locked_description_to_items_table.php
resources/css/app.css
resources/js/app.js
resources/js/components/Bucketlist.vue
resources/js/components/CodePanel.vue
resources/js/components/InteractionStory.vue
resources/js/views/ItemDetail.vue
resources/js/views/LockedItemDetail.vue
resources/js/views/PlaceDetail.vue
resources/js/views/RewardDetail.vue
resources/js/views/SectionDetail.vue
resources/lang/sk.json

feat: add locked item text

---

app/Http/Resources/ItemResource.php

Nsng 348 show roles to authorities

---

app/Http/Resources/ItemResource.php

Rework how the authorities are displayed on item

rework: authors/authorities names

---

vite.config.js

to fix 
the workaround from [freek.dev](https://freek.dev/2276-making-vite-and-valet-play-nice-together) is no longer necessary

update vite config to use host from the .env

---

resources/js/components/Bucketlist.vue
resources/lang/sk.json

update copy in the locked bucketlist

---

app/Http/Kernel.php
composer.json
composer.lock

update to laravel 10.
from now use `php 8.2`

update to laravel 10

---

package-lock.json
package.json
resources/js/bootstrap.js
resources/js/components/CodePanel.vue
resources/js/components/Header.vue

Update libraries
Fix breaking changes
Delete unused stuff
PS: install 20v of node

Nsng 399 upgrade libraries

---

app/Jobs/ImportSectionsJob.php

fix https://slovak-national-gallery.sentry.io/share/issue/b011a181227c468282771bea3ef3468f/

enable importing section without items from airtable

---

resources/js/composables/Survey.js

remove story condition from questionnaire start

Nsng 458 questionnaire condition

---

app/Http/Kernel.php
app/Jobs/ImportJob.php
composer.json
composer.lock
config/responsecache.php
config/scribe.php
routes/api.php

improve API performance by adding https://github.com/spatie/laravel-responsecache
@todo: consider calling `ResponseCache::clear();` after import? 
any preferred default for `RESPONSE_CACHE_LIFETIME`?

Nsng 403 cache api

---

composer.json
composer.lock

fix deployment
```
ERROR  There are no commands defined in the "scribe" namespace.
```

move knuckleswtf/scribe from require-dev key to require key

---

app/Models/DiscountCode.php
database/migrations/2023_12_06_123550_create_discount_codes_table.php
routes/api.php

Nsng 456 discount code api

---

app/CacheProfiles/LocalizeCacheProfile.php
config/responsecache.php

solved with adding [custom cache profile](https://github.com/spatie/laravel-responsecache?tab=readme-ov-file#creating-a-custom-cache-profile)

add LocalizeCacheProfile to include x-locale in cache hash

---

app/Http/Resources/ItemResource.php

filter out empty items in filteredLocalAuthoritiesNames in getAuthor() method

fix related_items author name formating
